language: erlang

sudo: required

services:
  - docker

before_install:
  - git clone https://github.com/inaka/elvis.git; cd elvis; rebar3 escriptize; sudo cp _build/default/bin/elvis /usr/bin; cd ..

notifications:
  email: false

otp_release:
  - 21.0
  - 20.3
  - 19.3

script:
  - set -e
  - elvis rock

  - echo "verifying rebar compilation"
  - rebar get-deps
  - rebar compile

  - make distclean
  - echo "verifying rebar3 compilation"
  - rebar3 compile

  - make distclean
  - make rel
  - make edoc
  - make xref
  - |
    OTP_VSN=`erl -noshell -eval 'io:format(erlang:system_info(otp_release)), halt(0)'`
    if [ $OTP_VSN -eq 21 ]; then
      # run dialyzer only in otp 21
      make dialyze
      # test against kafka 0.9 in otp 21
      export KAFKA_VERSION="0.9"
    fi
    if [ $OTP_VSN -eq 20 ]; then
      # test against kafka 0.10 in otp 20
      export KAFKA_VERSION="0.10"
    fi
    if [ $OTP_VSN -eq 19 ]; then
      # test against kafka 0.11 in otp 19
      export KAFKA_VERSION="0.11"
    fi
    make test-env
    make it
    # final full test against kafka 1.1
    export KAFKA_VERSION="1.1"
    make test-env
    make t
