version: '2'

services:
  zookeeper:
    image: "zmstone/kafka:${KAFKA_VERSION}"
    ports:
      - "2181:2181"
    container_name: zookeeper
    command: run zookeeper
  kafka_1:
    image: "zmstone/kafka:${KAFKA_VERSION}"
    container_name: 'kafka-1'
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9094:9094"
      - "9095:9095"
    environment:
      BROKER_ID: 0
      PLAINTEXT_PORT: 9092
      SSL_PORT: 9093
      SASL_SSL_PORT: 9094
      SASL_PLAINTEXT_PORT: 9095
  kafka_2:
    image: "zmstone/kafka:${KAFKA_VERSION}"
    container_name: 'kafka-2'
    ports:
      - "9192:9092"
      - "9193:9093"
      - "9194:9094"
      - "9195:9095"
    environment:
      BROKER_ID: 1
      PLAINTEXT_PORT: 9092
      SSL_PORT: 9093
      SASL_SSL_PORT: 9094
      SASL_PLAINTEXT_PORT: 9095

